import axios from "axios";
import React, { useState, useEffect } from "react";
import { StatusBar } from "expo-status-bar";
import { StyleSheet, View } from "react-native";
import { Text, Card, Paragraph, Divider } from "react-native-paper";
import {
  WiDaySunny,
  WiCloudy,
  WiDaySunnyOvercast,
  WiDayCloudyHigh,
  WiDayFog,
  WiFog,
  WiSprinkle,
  WiRaindrops,
  WiSleet,
  WiRainMix,
  WiRain,
  WiSnow,
  WiShowers,
  WiHail,
  WiThunderstorm,
  WiStormShowers,
  WiNa,
  WiWindDeg,
} from "react-icons/wi";

export default function App() {
  const [clima, setClima] = useState({});
  const [timeZone, setTimezone] = useState("");

  useEffect(() => {
    axios
      .get(
        "https://api.open-meteo.com/v1/forecast?latitude=-34.6118&longitude=-58.4173&current_weather=true&timezone=America/Argentina/Buenos_Aires"
      )
      .then((response) => {
        setTimezone(response.data.timezone);
        setClima(response.data.current_weather);
      })
      .catch(function (error) {
        console.log(error);
      });
  }, []);

  //Obtener la ciudad formateada
  function getCiudad() {
    const arrayCiudad = timeZone.split("/");
    const ciudad = arrayCiudad[2]?.replace("_", " ");
    return ciudad;
  }

  //Obtener la hora formateada
  function getHora() {
    const hora = clima.time;
    const date = new Date(hora).toLocaleString("es-ES", {
      hour: "numeric",
      minute: "numeric",
      hour12: false,
    });
    return date;
  }

  //Obtener el estado del clima
  function getWeatherEstado(x) {
    const estado = {
      0: "Despejado",
      1: "Parcialmente despejado",
      2: "Parcialmente Nublado",
      3: "Nublado",
      45: "Niebla",
      48: "Niebla espesa",
      51: "Llovizna ligera",
      53: "Llovizna moderada",
      55: "Llovizna intensa",
      56: "Aguanieve ligera",
      57: "Aguanieve densa",
      61: "Lluvia leve",
      63: "Lluvia moderada",
      65: "Lluvia intensa",
      66: "Lluvia helada ligera",
      67: "Lluvia healda intensa",
      71: "Nevada leve",
      73: "Nevada moderada",
      75: "Nevada intensa",
      77: "Granizo",
      80: "Chaparrones leves",
      81: "Chaparrones moderados",
      82: "Chaparrones violentos",
      85: "Nevadas aisladas leve",
      86: "Nevadas aisladas intenso",
      95: "Tormenta leve o moderada",
      96: "Tormenta con granizo leve",
      99: "Tormenta con granizo denso",
    };

    return estado[x] ?? <WiNa style={{ color: "white" }} />;
  }

  //Obtener el icono
  function getWeatherIcons(x) {
    const icons = {
      0: <WiDaySunny style={{ color: "yellow" }} />,
      1: <WiDaySunnyOvercast style={{ color: "white" }} />,
      2: <WiDayCloudyHigh style={{ color: "white" }} />,
      3: <WiCloudy style={{ color: "white" }} />,
      45: <WiDayFog style={{ color: "white" }} />,
      48: <WiFog style={{ color: "white" }} />,
      51: <WiSprinkle style={{ color: "white" }} />,
      53: <WiRaindrops style={{ color: "white" }} />,
      55: <WiRaindrops style={{ color: "white" }} />,
      56: <WiSleet style={{ color: "white" }} />,
      57: <WiSleet style={{ color: "white" }} />,
      61: <WiRain style={{ color: "white" }} />,
      63: <WiRain style={{ color: "white" }} />,
      65: <WiRain style={{ color: "white" }} />,
      66: <WiRainMix style={{ color: "white" }} />,
      67: <WiRainMix style={{ color: "white" }} />,
      71: <WiSnow style={{ color: "white" }} />,
      73: <WiSnow style={{ color: "white" }} />,
      75: <WiSnow style={{ color: "white" }} />,
      77: <WiHail style={{ color: "white" }} />,
      80: <WiShowers style={{ color: "white" }} />,
      81: <WiShowers style={{ color: "white" }} />,
      82: <WiShowers style={{ color: "white" }} />,
      85: <WiSnow style={{ color: "white" }} />,
      86: <WiSnow style={{ color: "white" }} />,
      95: <WiThunderstorm style={{ color: "white" }} />,
      96: <WiStormShowers style={{ color: "white" }} />,
      99: <WiStormShowers style={{ color: "white" }} />,
    };

    return icons[x] ?? <WiNa style={{ color: "white" }} />;
  }

  //Obtener la direccion del viento
  function getWindDirection(x) {
    const windDirection = {
      0: <WiWindDeg />,
      1: <WiWindDeg style={{ transform: "rotate(1deg)" }} />,
      2: <WiWindDeg style={{ transform: "rotate(2deg)" }} />,
      3: <WiWindDeg style={{ transform: "rotate(3deg)" }} />,
      4: <WiWindDeg style={{ transform: "rotate(4deg)" }} />,
      5: <WiWindDeg style={{ transform: "rotate(5deg)" }} />,
      6: <WiWindDeg style={{ transform: "rotate(6deg)" }} />,
      7: <WiWindDeg style={{ transform: "rotate(7deg)" }} />,
      8: <WiWindDeg style={{ transform: "rotate(8deg)" }} />,
      9: <WiWindDeg style={{ transform: "rotate(9deg)" }} />,
      10: <WiWindDeg style={{ transform: "rotate(10deg)" }} />,
      11: <WiWindDeg style={{ transform: "rotate(11deg)" }} />,
      12: <WiWindDeg style={{ transform: "rotate(12deg)" }} />,
      13: <WiWindDeg style={{ transform: "rotate(13deg)" }} />,
      14: <WiWindDeg style={{ transform: "rotate(14deg)" }} />,
      15: <WiWindDeg style={{ transform: "rotate(15deg)" }} />,
      16: <WiWindDeg style={{ transform: "rotate(16deg)" }} />,
      17: <WiWindDeg style={{ transform: "rotate(17deg)" }} />,
      18: <WiWindDeg style={{ transform: "rotate(18deg)" }} />,
      19: <WiWindDeg style={{ transform: "rotate(19deg)" }} />,
      20: <WiWindDeg style={{ transform: "rotate(20deg)" }} />,
      21: <WiWindDeg style={{ transform: "rotate(21deg)" }} />,
      22: <WiWindDeg style={{ transform: "rotate(22deg)" }} />,
      23: <WiWindDeg style={{ transform: "rotate(23deg)" }} />,
      24: <WiWindDeg style={{ transform: "rotate(24deg)" }} />,
      25: <WiWindDeg style={{ transform: "rotate(25deg)" }} />,
      26: <WiWindDeg style={{ transform: "rotate(26deg)" }} />,
      27: <WiWindDeg style={{ transform: "rotate(27deg)" }} />,
      28: <WiWindDeg style={{ transform: "rotate(28deg)" }} />,
      29: <WiWindDeg style={{ transform: "rotate(29deg)" }} />,
      30: <WiWindDeg style={{ transform: "rotate(30deg)" }} />,
      31: <WiWindDeg style={{ transform: "rotate(31deg)" }} />,
      32: <WiWindDeg style={{ transform: "rotate(32deg)" }} />,
      33: <WiWindDeg style={{ transform: "rotate(33deg)" }} />,
      34: <WiWindDeg style={{ transform: "rotate(34deg)" }} />,
      35: <WiWindDeg style={{ transform: "rotate(35deg)" }} />,
      36: <WiWindDeg style={{ transform: "rotate(36deg)" }} />,
      37: <WiWindDeg style={{ transform: "rotate(37deg)" }} />,
      38: <WiWindDeg style={{ transform: "rotate(38deg)" }} />,
      39: <WiWindDeg style={{ transform: "rotate(39deg)" }} />,
      40: <WiWindDeg style={{ transform: "rotate(40deg)" }} />,
      41: <WiWindDeg style={{ transform: "rotate(41deg)" }} />,
      42: <WiWindDeg style={{ transform: "rotate(42deg)" }} />,
      43: <WiWindDeg style={{ transform: "rotate(43deg)" }} />,
      44: <WiWindDeg style={{ transform: "rotate(44deg)" }} />,
      45: <WiWindDeg style={{ transform: "rotate(45deg)" }} />,
      46: <WiWindDeg style={{ transform: "rotate(46deg)" }} />,
      47: <WiWindDeg style={{ transform: "rotate(47deg)" }} />,
      48: <WiWindDeg style={{ transform: "rotate(48deg)" }} />,
      49: <WiWindDeg style={{ transform: "rotate(49deg)" }} />,
      50: <WiWindDeg style={{ transform: "rotate(50deg)" }} />,
      51: <WiWindDeg style={{ transform: "rotate(51deg)" }} />,
      52: <WiWindDeg style={{ transform: "rotate(52deg)" }} />,
      53: <WiWindDeg style={{ transform: "rotate(53deg)" }} />,
      54: <WiWindDeg style={{ transform: "rotate(54deg)" }} />,
      55: <WiWindDeg style={{ transform: "rotate(55deg)" }} />,
      56: <WiWindDeg style={{ transform: "rotate(56deg)" }} />,
      57: <WiWindDeg style={{ transform: "rotate(57deg)" }} />,
      58: <WiWindDeg style={{ transform: "rotate(58deg)" }} />,
      59: <WiWindDeg style={{ transform: "rotate(59deg)" }} />,
      60: <WiWindDeg style={{ transform: "rotate(60deg)" }} />,
      61: <WiWindDeg style={{ transform: "rotate(61deg)" }} />,
      62: <WiWindDeg style={{ transform: "rotate(62deg)" }} />,
      63: <WiWindDeg style={{ transform: "rotate(63deg)" }} />,
      64: <WiWindDeg style={{ transform: "rotate(64deg)" }} />,
      65: <WiWindDeg style={{ transform: "rotate(65deg)" }} />,
      66: <WiWindDeg style={{ transform: "rotate(66deg)" }} />,
      67: <WiWindDeg style={{ transform: "rotate(67deg)" }} />,
      68: <WiWindDeg style={{ transform: "rotate(68deg)" }} />,
      69: <WiWindDeg style={{ transform: "rotate(69deg)" }} />,
      70: <WiWindDeg style={{ transform: "rotate(70deg)" }} />,
      71: <WiWindDeg style={{ transform: "rotate(71deg)" }} />,
      72: <WiWindDeg style={{ transform: "rotate(72deg)" }} />,
      73: <WiWindDeg style={{ transform: "rotate(73deg)" }} />,
      74: <WiWindDeg style={{ transform: "rotate(74deg)" }} />,
      75: <WiWindDeg style={{ transform: "rotate(75deg)" }} />,
      76: <WiWindDeg style={{ transform: "rotate(76deg)" }} />,
      77: <WiWindDeg style={{ transform: "rotate(77deg)" }} />,
      78: <WiWindDeg style={{ transform: "rotate(78deg)" }} />,
      79: <WiWindDeg style={{ transform: "rotate(79deg)" }} />,
      80: <WiWindDeg style={{ transform: "rotate(80deg)" }} />,
      81: <WiWindDeg style={{ transform: "rotate(81deg)" }} />,
      82: <WiWindDeg style={{ transform: "rotate(82deg)" }} />,
      83: <WiWindDeg style={{ transform: "rotate(83deg)" }} />,
      84: <WiWindDeg style={{ transform: "rotate(84deg)" }} />,
      85: <WiWindDeg style={{ transform: "rotate(85deg)" }} />,
      86: <WiWindDeg style={{ transform: "rotate(86deg)" }} />,
      87: <WiWindDeg style={{ transform: "rotate(87deg)" }} />,
      88: <WiWindDeg style={{ transform: "rotate(88deg)" }} />,
      89: <WiWindDeg style={{ transform: "rotate(89deg)" }} />,
      90: <WiWindDeg style={{ transform: "rotate(90deg)" }} />,
      91: <WiWindDeg style={{ transform: "rotate(91deg)" }} />,
      92: <WiWindDeg style={{ transform: "rotate(92deg)" }} />,
      93: <WiWindDeg style={{ transform: "rotate(93deg)" }} />,
      94: <WiWindDeg style={{ transform: "rotate(94deg)" }} />,
      95: <WiWindDeg style={{ transform: "rotate(95deg)" }} />,
      96: <WiWindDeg style={{ transform: "rotate(96deg)" }} />,
      97: <WiWindDeg style={{ transform: "rotate(97deg)" }} />,
      98: <WiWindDeg style={{ transform: "rotate(98deg)" }} />,
      99: <WiWindDeg style={{ transform: "rotate(99deg)" }} />,
      100: <WiWindDeg style={{ transform: "rotate(100deg)" }} />,
      101: <WiWindDeg style={{ transform: "rotate(101deg)" }} />,
      102: <WiWindDeg style={{ transform: "rotate(102deg)" }} />,
      103: <WiWindDeg style={{ transform: "rotate(103deg)" }} />,
      104: <WiWindDeg style={{ transform: "rotate(104deg)" }} />,
      105: <WiWindDeg style={{ transform: "rotate(105deg)" }} />,
      106: <WiWindDeg style={{ transform: "rotate(106deg)" }} />,
      107: <WiWindDeg style={{ transform: "rotate(107deg)" }} />,
      108: <WiWindDeg style={{ transform: "rotate(108deg)" }} />,
      109: <WiWindDeg style={{ transform: "rotate(109deg)" }} />,
      110: <WiWindDeg style={{ transform: "rotate(110deg)" }} />,
      111: <WiWindDeg style={{ transform: "rotate(111deg)" }} />,
      112: <WiWindDeg style={{ transform: "rotate(112deg)" }} />,
      113: <WiWindDeg style={{ transform: "rotate(113deg)" }} />,
      114: <WiWindDeg style={{ transform: "rotate(114deg)" }} />,
      115: <WiWindDeg style={{ transform: "rotate(115deg)" }} />,
      116: <WiWindDeg style={{ transform: "rotate(116deg)" }} />,
      117: <WiWindDeg style={{ transform: "rotate(117deg)" }} />,
      118: <WiWindDeg style={{ transform: "rotate(118deg)" }} />,
      119: <WiWindDeg style={{ transform: "rotate(119deg)" }} />,
      120: <WiWindDeg style={{ transform: "rotate(120deg)" }} />,
      121: <WiWindDeg style={{ transform: "rotate(121deg)" }} />,
      122: <WiWindDeg style={{ transform: "rotate(122deg)" }} />,
      123: <WiWindDeg style={{ transform: "rotate(123deg)" }} />,
      124: <WiWindDeg style={{ transform: "rotate(124deg)" }} />,
      125: <WiWindDeg style={{ transform: "rotate(125deg)" }} />,
      126: <WiWindDeg style={{ transform: "rotate(126deg)" }} />,
      127: <WiWindDeg style={{ transform: "rotate(127deg)" }} />,
      128: <WiWindDeg style={{ transform: "rotate(128deg)" }} />,
      129: <WiWindDeg style={{ transform: "rotate(129deg)" }} />,
      130: <WiWindDeg style={{ transform: "rotate(130deg)" }} />,
      131: <WiWindDeg style={{ transform: "rotate(131deg)" }} />,
      132: <WiWindDeg style={{ transform: "rotate(132deg)" }} />,
      133: <WiWindDeg style={{ transform: "rotate(133deg)" }} />,
      134: <WiWindDeg style={{ transform: "rotate(134deg)" }} />,
      135: <WiWindDeg style={{ transform: "rotate(135deg)" }} />,
      136: <WiWindDeg style={{ transform: "rotate(136deg)" }} />,
      137: <WiWindDeg style={{ transform: "rotate(137deg)" }} />,
      138: <WiWindDeg style={{ transform: "rotate(138deg)" }} />,
      139: <WiWindDeg style={{ transform: "rotate(139deg)" }} />,
      140: <WiWindDeg style={{ transform: "rotate(140deg)" }} />,
      141: <WiWindDeg style={{ transform: "rotate(141deg)" }} />,
      142: <WiWindDeg style={{ transform: "rotate(142deg)" }} />,
      143: <WiWindDeg style={{ transform: "rotate(143deg)" }} />,
      144: <WiWindDeg style={{ transform: "rotate(144deg)" }} />,
      145: <WiWindDeg style={{ transform: "rotate(145deg)" }} />,
      146: <WiWindDeg style={{ transform: "rotate(146deg)" }} />,
      147: <WiWindDeg style={{ transform: "rotate(147deg)" }} />,
      148: <WiWindDeg style={{ transform: "rotate(148deg)" }} />,
      149: <WiWindDeg style={{ transform: "rotate(149deg)" }} />,
      150: <WiWindDeg style={{ transform: "rotate(150deg)" }} />,
      151: <WiWindDeg style={{ transform: "rotate(151deg)" }} />,
      152: <WiWindDeg style={{ transform: "rotate(152deg)" }} />,
      153: <WiWindDeg style={{ transform: "rotate(153deg)" }} />,
      154: <WiWindDeg style={{ transform: "rotate(154deg)" }} />,
      155: <WiWindDeg style={{ transform: "rotate(155deg)" }} />,
      156: <WiWindDeg style={{ transform: "rotate(156deg)" }} />,
      157: <WiWindDeg style={{ transform: "rotate(157deg)" }} />,
      158: <WiWindDeg style={{ transform: "rotate(158deg)" }} />,
      159: <WiWindDeg style={{ transform: "rotate(159deg)" }} />,
      160: <WiWindDeg style={{ transform: "rotate(160deg)" }} />,
      161: <WiWindDeg style={{ transform: "rotate(161deg)" }} />,
      162: <WiWindDeg style={{ transform: "rotate(162deg)" }} />,
      163: <WiWindDeg style={{ transform: "rotate(163deg)" }} />,
      164: <WiWindDeg style={{ transform: "rotate(164deg)" }} />,
      165: <WiWindDeg style={{ transform: "rotate(165deg)" }} />,
      166: <WiWindDeg style={{ transform: "rotate(166deg)" }} />,
      167: <WiWindDeg style={{ transform: "rotate(167deg)" }} />,
      168: <WiWindDeg style={{ transform: "rotate(168deg)" }} />,
      169: <WiWindDeg style={{ transform: "rotate(169deg)" }} />,
      170: <WiWindDeg style={{ transform: "rotate(170deg)" }} />,
      171: <WiWindDeg style={{ transform: "rotate(171deg)" }} />,
      172: <WiWindDeg style={{ transform: "rotate(172deg)" }} />,
      173: <WiWindDeg style={{ transform: "rotate(173deg)" }} />,
      174: <WiWindDeg style={{ transform: "rotate(174deg)" }} />,
      175: <WiWindDeg style={{ transform: "rotate(175deg)" }} />,
      176: <WiWindDeg style={{ transform: "rotate(176deg)" }} />,
      177: <WiWindDeg style={{ transform: "rotate(177deg)" }} />,
      178: <WiWindDeg style={{ transform: "rotate(178deg)" }} />,
      179: <WiWindDeg style={{ transform: "rotate(179deg)" }} />,
      180: <WiWindDeg style={{ transform: "rotate(180deg)" }} />,
      181: <WiWindDeg style={{ transform: "rotate(181deg)" }} />,
      182: <WiWindDeg style={{ transform: "rotate(182deg)" }} />,
      183: <WiWindDeg style={{ transform: "rotate(183deg)" }} />,
      184: <WiWindDeg style={{ transform: "rotate(184deg)" }} />,
      185: <WiWindDeg style={{ transform: "rotate(185deg)" }} />,
      186: <WiWindDeg style={{ transform: "rotate(186deg)" }} />,
      187: <WiWindDeg style={{ transform: "rotate(187deg)" }} />,
      188: <WiWindDeg style={{ transform: "rotate(188deg)" }} />,
      189: <WiWindDeg style={{ transform: "rotate(189deg)" }} />,
      190: <WiWindDeg style={{ transform: "rotate(190deg)" }} />,
      191: <WiWindDeg style={{ transform: "rotate(191deg)" }} />,
      192: <WiWindDeg style={{ transform: "rotate(192deg)" }} />,
      193: <WiWindDeg style={{ transform: "rotate(193deg)" }} />,
      194: <WiWindDeg style={{ transform: "rotate(194deg)" }} />,
      195: <WiWindDeg style={{ transform: "rotate(195deg)" }} />,
      196: <WiWindDeg style={{ transform: "rotate(196deg)" }} />,
      197: <WiWindDeg style={{ transform: "rotate(197deg)" }} />,
      198: <WiWindDeg style={{ transform: "rotate(198deg)" }} />,
      199: <WiWindDeg style={{ transform: "rotate(199deg)" }} />,
      200: <WiWindDeg style={{ transform: "rotate(200deg)" }} />,
      201: <WiWindDeg style={{ transform: "rotate(201deg)" }} />,
      202: <WiWindDeg style={{ transform: "rotate(202deg)" }} />,
      203: <WiWindDeg style={{ transform: "rotate(203deg)" }} />,
      204: <WiWindDeg style={{ transform: "rotate(204deg)" }} />,
      205: <WiWindDeg style={{ transform: "rotate(205deg)" }} />,
      206: <WiWindDeg style={{ transform: "rotate(206deg)" }} />,
      207: <WiWindDeg style={{ transform: "rotate(207deg)" }} />,
      208: <WiWindDeg style={{ transform: "rotate(208deg)" }} />,
      209: <WiWindDeg style={{ transform: "rotate(209deg)" }} />,
      210: <WiWindDeg style={{ transform: "rotate(210deg)" }} />,
      211: <WiWindDeg style={{ transform: "rotate(211deg)" }} />,
      212: <WiWindDeg style={{ transform: "rotate(212deg)" }} />,
      213: <WiWindDeg style={{ transform: "rotate(213deg)" }} />,
      214: <WiWindDeg style={{ transform: "rotate(214deg)" }} />,
      215: <WiWindDeg style={{ transform: "rotate(215deg)" }} />,
      216: <WiWindDeg style={{ transform: "rotate(216deg)" }} />,
      217: <WiWindDeg style={{ transform: "rotate(217deg)" }} />,
      218: <WiWindDeg style={{ transform: "rotate(218deg)" }} />,
      219: <WiWindDeg style={{ transform: "rotate(219deg)" }} />,
      220: <WiWindDeg style={{ transform: "rotate(220deg)" }} />,
      221: <WiWindDeg style={{ transform: "rotate(221deg)" }} />,
      222: <WiWindDeg style={{ transform: "rotate(222deg)" }} />,
      223: <WiWindDeg style={{ transform: "rotate(223deg)" }} />,
      224: <WiWindDeg style={{ transform: "rotate(224deg)" }} />,
      225: <WiWindDeg style={{ transform: "rotate(225deg)" }} />,
      226: <WiWindDeg style={{ transform: "rotate(226deg)" }} />,
      227: <WiWindDeg style={{ transform: "rotate(227deg)" }} />,
      228: <WiWindDeg style={{ transform: "rotate(228deg)" }} />,
      229: <WiWindDeg style={{ transform: "rotate(229deg)" }} />,
      230: <WiWindDeg style={{ transform: "rotate(230deg)" }} />,
      231: <WiWindDeg style={{ transform: "rotate(231deg)" }} />,
      232: <WiWindDeg style={{ transform: "rotate(232deg)" }} />,
      233: <WiWindDeg style={{ transform: "rotate(233deg)" }} />,
      234: <WiWindDeg style={{ transform: "rotate(234deg)" }} />,
      235: <WiWindDeg style={{ transform: "rotate(235deg)" }} />,
      236: <WiWindDeg style={{ transform: "rotate(236deg)" }} />,
      237: <WiWindDeg style={{ transform: "rotate(237deg)" }} />,
      238: <WiWindDeg style={{ transform: "rotate(238deg)" }} />,
      239: <WiWindDeg style={{ transform: "rotate(239deg)" }} />,
      240: <WiWindDeg style={{ transform: "rotate(240deg)" }} />,
      241: <WiWindDeg style={{ transform: "rotate(241deg)" }} />,
      242: <WiWindDeg style={{ transform: "rotate(242deg)" }} />,
      243: <WiWindDeg style={{ transform: "rotate(243deg)" }} />,
      244: <WiWindDeg style={{ transform: "rotate(244deg)" }} />,
      245: <WiWindDeg style={{ transform: "rotate(245deg)" }} />,
      246: <WiWindDeg style={{ transform: "rotate(246deg)" }} />,
      247: <WiWindDeg style={{ transform: "rotate(247deg)" }} />,
      248: <WiWindDeg style={{ transform: "rotate(248deg)" }} />,
      249: <WiWindDeg style={{ transform: "rotate(249deg)" }} />,
      250: <WiWindDeg style={{ transform: "rotate(250deg)" }} />,
      251: <WiWindDeg style={{ transform: "rotate(251deg)" }} />,
      252: <WiWindDeg style={{ transform: "rotate(252deg)" }} />,
      253: <WiWindDeg style={{ transform: "rotate(253deg)" }} />,
      254: <WiWindDeg style={{ transform: "rotate(254deg)" }} />,
      255: <WiWindDeg style={{ transform: "rotate(255deg)" }} />,
      256: <WiWindDeg style={{ transform: "rotate(256deg)" }} />,
      257: <WiWindDeg style={{ transform: "rotate(257deg)" }} />,
      258: <WiWindDeg style={{ transform: "rotate(258deg)" }} />,
      259: <WiWindDeg style={{ transform: "rotate(259deg)" }} />,
      260: <WiWindDeg style={{ transform: "rotate(260deg)" }} />,
      261: <WiWindDeg style={{ transform: "rotate(261deg)" }} />,
      262: <WiWindDeg style={{ transform: "rotate(262deg)" }} />,
      263: <WiWindDeg style={{ transform: "rotate(263deg)" }} />,
      264: <WiWindDeg style={{ transform: "rotate(264deg)" }} />,
      265: <WiWindDeg style={{ transform: "rotate(265deg)" }} />,
      266: <WiWindDeg style={{ transform: "rotate(266deg)" }} />,
      267: <WiWindDeg style={{ transform: "rotate(267deg)" }} />,
      268: <WiWindDeg style={{ transform: "rotate(268deg)" }} />,
      269: <WiWindDeg style={{ transform: "rotate(269deg)" }} />,
      270: <WiWindDeg style={{ transform: "rotate(270deg)" }} />,
      271: <WiWindDeg style={{ transform: "rotate(271deg)" }} />,
      272: <WiWindDeg style={{ transform: "rotate(272deg)" }} />,
      273: <WiWindDeg style={{ transform: "rotate(273deg)" }} />,
      274: <WiWindDeg style={{ transform: "rotate(274deg)" }} />,
      275: <WiWindDeg style={{ transform: "rotate(275deg)" }} />,
      276: <WiWindDeg style={{ transform: "rotate(276deg)" }} />,
      277: <WiWindDeg style={{ transform: "rotate(277deg)" }} />,
      278: <WiWindDeg style={{ transform: "rotate(278deg)" }} />,
      279: <WiWindDeg style={{ transform: "rotate(279deg)" }} />,
      280: <WiWindDeg style={{ transform: "rotate(280deg)" }} />,
      281: <WiWindDeg style={{ transform: "rotate(281deg)" }} />,
      282: <WiWindDeg style={{ transform: "rotate(282deg)" }} />,
      283: <WiWindDeg style={{ transform: "rotate(283deg)" }} />,
      284: <WiWindDeg style={{ transform: "rotate(284deg)" }} />,
      285: <WiWindDeg style={{ transform: "rotate(285deg)" }} />,
      286: <WiWindDeg style={{ transform: "rotate(286deg)" }} />,
      287: <WiWindDeg style={{ transform: "rotate(287deg)" }} />,
      288: <WiWindDeg style={{ transform: "rotate(288deg)" }} />,
      289: <WiWindDeg style={{ transform: "rotate(289deg)" }} />,
      290: <WiWindDeg style={{ transform: "rotate(290deg)" }} />,
      291: <WiWindDeg style={{ transform: "rotate(291deg)" }} />,
      292: <WiWindDeg style={{ transform: "rotate(292deg)" }} />,
      293: <WiWindDeg style={{ transform: "rotate(293deg)" }} />,
      294: <WiWindDeg style={{ transform: "rotate(294deg)" }} />,
      295: <WiWindDeg style={{ transform: "rotate(295deg)" }} />,
      296: <WiWindDeg style={{ transform: "rotate(296deg)" }} />,
      297: <WiWindDeg style={{ transform: "rotate(297deg)" }} />,
      298: <WiWindDeg style={{ transform: "rotate(298deg)" }} />,
      299: <WiWindDeg style={{ transform: "rotate(299deg)" }} />,
      300: <WiWindDeg style={{ transform: "rotate(300deg)" }} />,
      301: <WiWindDeg style={{ transform: "rotate(301deg)" }} />,
      302: <WiWindDeg style={{ transform: "rotate(302deg)" }} />,
      303: <WiWindDeg style={{ transform: "rotate(303deg)" }} />,
      304: <WiWindDeg style={{ transform: "rotate(304deg)" }} />,
      305: <WiWindDeg style={{ transform: "rotate(305deg)" }} />,
      306: <WiWindDeg style={{ transform: "rotate(306deg)" }} />,
      307: <WiWindDeg style={{ transform: "rotate(307deg)" }} />,
      308: <WiWindDeg style={{ transform: "rotate(308deg)" }} />,
      309: <WiWindDeg style={{ transform: "rotate(309deg)" }} />,
      310: <WiWindDeg style={{ transform: "rotate(310deg)" }} />,
      311: <WiWindDeg style={{ transform: "rotate(311deg)" }} />,
      312: <WiWindDeg style={{ transform: "rotate(312deg)" }} />,
      313: <WiWindDeg style={{ transform: "rotate(313deg)" }} />,
      314: <WiWindDeg style={{ transform: "rotate(314deg)" }} />,
      315: <WiWindDeg style={{ transform: "rotate(315deg)" }} />,
      316: <WiWindDeg style={{ transform: "rotate(316deg)" }} />,
      317: <WiWindDeg style={{ transform: "rotate(317deg)" }} />,
      318: <WiWindDeg style={{ transform: "rotate(318deg)" }} />,
      319: <WiWindDeg style={{ transform: "rotate(319deg)" }} />,
      320: <WiWindDeg style={{ transform: "rotate(320deg)" }} />,
      321: <WiWindDeg style={{ transform: "rotate(321deg)" }} />,
      322: <WiWindDeg style={{ transform: "rotate(322deg)" }} />,
      323: <WiWindDeg style={{ transform: "rotate(323deg)" }} />,
      324: <WiWindDeg style={{ transform: "rotate(324deg)" }} />,
      325: <WiWindDeg style={{ transform: "rotate(325deg)" }} />,
      326: <WiWindDeg style={{ transform: "rotate(326deg)" }} />,
      327: <WiWindDeg style={{ transform: "rotate(327deg)" }} />,
      328: <WiWindDeg style={{ transform: "rotate(328deg)" }} />,
      329: <WiWindDeg style={{ transform: "rotate(329deg)" }} />,
      330: <WiWindDeg style={{ transform: "rotate(330deg)" }} />,
      331: <WiWindDeg style={{ transform: "rotate(331deg)" }} />,
      332: <WiWindDeg style={{ transform: "rotate(332deg)" }} />,
      333: <WiWindDeg style={{ transform: "rotate(333deg)" }} />,
      334: <WiWindDeg style={{ transform: "rotate(334deg)" }} />,
      335: <WiWindDeg style={{ transform: "rotate(335deg)" }} />,
      336: <WiWindDeg style={{ transform: "rotate(336deg)" }} />,
      337: <WiWindDeg style={{ transform: "rotate(337deg)" }} />,
      338: <WiWindDeg style={{ transform: "rotate(338deg)" }} />,
      339: <WiWindDeg style={{ transform: "rotate(339deg)" }} />,
      340: <WiWindDeg style={{ transform: "rotate(340deg)" }} />,
      341: <WiWindDeg style={{ transform: "rotate(341deg)" }} />,
      342: <WiWindDeg style={{ transform: "rotate(342deg)" }} />,
      343: <WiWindDeg style={{ transform: "rotate(343deg)" }} />,
      344: <WiWindDeg style={{ transform: "rotate(344deg)" }} />,
      345: <WiWindDeg style={{ transform: "rotate(345deg)" }} />,
      346: <WiWindDeg style={{ transform: "rotate(346deg)" }} />,
      347: <WiWindDeg style={{ transform: "rotate(347deg)" }} />,
      348: <WiWindDeg style={{ transform: "rotate(348deg)" }} />,
      349: <WiWindDeg style={{ transform: "rotate(349deg)" }} />,
      350: <WiWindDeg style={{ transform: "rotate(350deg)" }} />,
      351: <WiWindDeg style={{ transform: "rotate(351deg)" }} />,
      352: <WiWindDeg style={{ transform: "rotate(352deg)" }} />,
      353: <WiWindDeg style={{ transform: "rotate(353deg)" }} />,
      354: <WiWindDeg style={{ transform: "rotate(354deg)" }} />,
      355: <WiWindDeg style={{ transform: "rotate(355deg)" }} />,
      356: <WiWindDeg style={{ transform: "rotate(356deg)" }} />,
      357: <WiWindDeg style={{ transform: "rotate(357deg)" }} />,
      358: <WiWindDeg style={{ transform: "rotate(358deg)" }} />,
      359: <WiWindDeg style={{ transform: "rotate(359deg)" }} />,
    };

    return windDirection[x] ?? <WiNa style={{ color: "white" }} />;
  }

  return (
    <View style={styles.container}>
      <Text variant="headlineMedium" style={{ color: "white" }}>
        {getCiudad()}
      </Text>
      <Text variant="displayMedium" style={{ color: "white" }}>
        {clima.temperature}°
      </Text>
      <Text style={styles.icon}>{getWeatherIcons(clima.weathercode)}</Text>
      <Text variant="titleMedium" style={{ color: "white" }}>
        {getWeatherEstado(clima.weathercode)}
      </Text>
      <Card style={styles.card}>
        <Card.Content>
          <Paragraph style={styles.cardParagraph}>
            {getWeatherEstado(clima.weathercode)}, condiciones esperadas para
            las {getHora()}.
          </Paragraph>
          <Divider />
          <View style={styles.viewList}>
            {/* ITEM 1 */}
            <View style={styles.itemList}>
              <Text variant="bodySmall" style={{ color: "white" }}>
                {clima.windspeed} km/h
              </Text>
              <Text style={styles.winddirection}>
                {getWindDirection(clima.winddirection)}
              </Text>
            </View>
          </View>
        </Card.Content>
      </Card>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundImage: "linear-gradient(180deg, #2ab5fa 10%, #4C83FF 90%)",
    alignItems: "center",
    justifyContent: "center",
    fontFamily:
      "SF Pro Display,SF Pro Icons,Helvetica Neue,Helvetica,Arial,sans-serif",
    color: "#ffffff",
  },
  card: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    marginTop: 20,
    width: "90%",
    height: "auto",
    borderRadius: 20,
  },
  cardParagraph: {
    marginBottom: 10,
    color: "white",
  },
  viewList: {
    marginTop: 10,
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
  },
  itemList: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  icon: {
    fontSize: 40,
  },
  winddirection: {
    color: "white",
    fontSize: 25,
  },
});
